 db:
  image: mysql:5.7
  container_name: cattle-db
  restart: always
  ports:
   - "3310:3306"
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: cattle-api
